services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_test
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  python-app:
    build: .
    container_name: python_test
    depends_on:
      - rabbitmq
    working_dir: /app
    volumes:
      - .:/app
    environment:
    # os.environ.get("RUN_MODE")  با این مقدار دهی مقدار اولیه رانمود زمان اجرا ست میشه و با دستور روبرو قابل خواندن
      RUN_MODE: DEBUG

volumes:
  rabbitmq_data: